name: Metrics
on:
  # Schedule daily updates
  schedule: [{cron: "0 0 * * *"}]
  # (optional) Run workflow manually
  workflow_dispatch:
  # (optional) Run workflow when pushing on master/main
  push: {branches: ["master", "main"]}
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    #environment: 
    #  name: production
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@master
        with:
          config_timezone: Europe/Copenhagen
          retries: 3
          retries_delay: 300
          #output_action: pull-request-squash
          template: terminal
          filename: metrics.terminal.svg
          token: ${{ secrets.METRICS_TOKEN }}
          base: header, metadata
