name: "TryHackMe Update Badge"

on:
  schedule:
    # Make it run every 24 hour
    - cron: '0 0 * * *'
  workflow_dispatch:
jobs:
  tryhackme-badge-update:
    name: Update this repo's tryhackme badge with the latest tryhackme image badge
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3
      - uses: p4p1/tryhackme-badge-workflow@main
        with:
          # Replace with your tryhackme username
          username: "SkyBirdDK"
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
